apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nn
  name: nn
spec:
  initContainers:
  - args:
    - /bin/sh
    - -c
    - wget -O /work-dir/index.html http://neverssl.com/online
    image: busybox
    name: bb
    resources: {}
    volumeMounts:
    - mountPath: /work-dir
      name: cache-volume
  containers:
  - name: nn
    image: nginx
    ports:
      - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
