apiVersion: batch/v1
kind: Job
metadata:
  name: j
spec:
  backoffLimit: 60
  parallelism: 3
  completions: 3
  template:
    spec:
      containers:
      - image: nginx
        name: j
        resources: {}
      restartPolicy: Never

      # k create job j --dry-run=client --image=nginx -o yaml