apiVersion: v1
kind: Pod
metadata: 
  name: nginx
  labels: 
    app: nginx
    tier: frontend
spec: 
  containers: 
    - name: container1
      image: nginx

# Kubectl logs  -f nginx container1  - view logs of containe1 of pod nginx
