apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
  - name: webapp
    image: kodekloud/event-simulator
    volumeMounts:
    - name: vol
      mountPath: /log
  volumes:
  - name: vol
    persistentVolumeClaim:
        claimName: claim-log-1
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}