apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    my-label: test
  name: pod1
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - hostname > /tmp/hostname && sleep 1d
    image: bash
    name: pod1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
