apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: jj
spec:
  activeDeadlineSeconds: 30
  completions: 5
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: nginx
        name: jj
        resources: {}
      restartPolicy: Never
status: {}
