apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    command: [ "/bin/sh","-c","ls /etc/lala" ]
    resources: {}
    volumeMounts:
      - name: config-volume
        mountPath: /etc/lala
  volumes:
    - name: config-volume
      configMap:
        name: cmvolume
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}