apiVersion: v1
kind: Pod
metadata: 
  name: nginx
  labels: 
    app: nginx
    tier: frontend
spec: 
  containers: 
    - name: nginx
      image: nginx
      args:
      - sleep
      - "1000"
      imagePullPolicy: Always
      resources:
        limits:
          cpu: "2"
          memory: 20Mi
        requests:
          cpu: "1"
          memory: 5Mi
